# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ECGCustomAlertView' do
  pod 'Masonry', '~> 1.0.2'
  pod 'ECGLayoutConstraint', '~> 1.0.6'
  pod 'MBProgressHUD', '~> 1.0.0'

end
